"""cascade on delete

Revision ID: 064dea6f0f88
Revises: 150c15c934f1
Create Date: 2023-09-10 17:45:23.503966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '064dea6f0f88'
down_revision: Union[str, None] = '150c15c934f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


fk1 = 'tbl_course_faculty_ibfk_1'
fk2 = 'tbl_course_restriction_ibfk_1'
fk3 = 'tbl_meeting_ibfk_1'
fk4 = 'tbl_word_course_data_ibfk_2'

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(fk1, 'tbl_course_faculty', type_='foreignkey')
    op.create_foreign_key(fk1, 'tbl_course_faculty', 'tbl_course_data', ['course_data_id'], ['course_data_id'], ondelete='CASCADE')
    op.drop_constraint(fk2, 'tbl_course_restriction', type_='foreignkey')
    op.create_foreign_key(fk2, 'tbl_course_restriction', 'tbl_course_data', ['course_data_id'], ['course_data_id'], ondelete='CASCADE')
    op.drop_constraint(fk3, 'tbl_meeting', type_='foreignkey')
    op.create_foreign_key(fk3, 'tbl_meeting', 'tbl_course_data', ['course_data_id'], ['course_data_id'], ondelete='CASCADE')
    op.drop_constraint(fk4, 'tbl_word_course_data', type_='foreignkey')
    op.create_foreign_key(fk4, 'tbl_word_course_data', 'tbl_course_data', ['course_data_id'], ['course_data_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(fk4, 'tbl_word_course_data', type_='foreignkey')
    op.create_foreign_key(fk4, 'tbl_word_course_data', 'tbl_course_data', ['course_data_id'], ['course_data_id'])
    op.drop_constraint(fk3, 'tbl_meeting', type_='foreignkey')
    op.create_foreign_key(fk3, 'tbl_meeting', 'tbl_course_data', ['course_data_id'], ['course_data_id'])
    op.drop_constraint(fk2, 'tbl_course_restriction', type_='foreignkey')
    op.create_foreign_key(fk2, 'tbl_course_restriction', 'tbl_course_data', ['course_data_id'], ['course_data_id'])
    op.drop_constraint(fk1, 'tbl_course_faculty', type_='foreignkey')
    op.create_foreign_key(fk1, 'tbl_course_faculty', 'tbl_course_data', ['course_data_id'], ['course_data_id'])
    # ### end Alembic commands ###
