"""Add scrape_id to tbl_meeting

Revision ID: 150c15c934f1
Revises: b236e35a544c
Create Date: 2023-09-09 14:40:09.853007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "150c15c934f1"
down_revision: Union[str, None] = "b236e35a544c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tbl_meeting", sa.Column("scrape_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "tbl_meeting", "tbl_scrape_history", ["scrape_id"], ["scrape_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tbl_meeting", type_="foreignkey")
    op.drop_column("tbl_meeting", "scrape_id")
    # ### end Alembic commands ###
