"""legacy database

Revision ID: b236e35a544c
Revises: 
Create Date: 2023-09-09 14:31:38.745548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b236e35a544c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tbl_browser",
        sa.Column("browser_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("browser_name", sa.VARCHAR(length=128), nullable=True),
        sa.Column("browser_version", sa.VARCHAR(length=128), nullable=True),
        sa.PrimaryKeyConstraint("browser_id"),
    )
    op.create_table(
        "tbl_classtype",
        sa.Column("class_type_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("class_type", sa.VARCHAR(length=128), nullable=True),
        sa.PrimaryKeyConstraint("class_type_id"),
    )
    op.create_table(
        "tbl_operating_system",
        sa.Column("os_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("os_name", sa.VARCHAR(length=128), nullable=True),
        sa.PrimaryKeyConstraint("os_id"),
    )
    op.create_table(
        "tbl_report_type",
        sa.Column("report_type_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("report_type_name", sa.VARCHAR(length=128), nullable=True),
        sa.Column("report_type_description", sa.VARCHAR(length=512), nullable=True),
        sa.PrimaryKeyConstraint("report_type_id"),
    )
    op.create_table(
        "tbl_restriction_type",
        sa.Column("restriction_type_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("restriction_type", sa.VARCHAR(length=128), nullable=True),
        sa.PrimaryKeyConstraint("restriction_type_id"),
    )
    op.create_table(
        "tbl_scrape_history",
        sa.Column("scrape_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scrape_time", sa.TIMESTAMP(), nullable=True),
        sa.Column("scrape_time_finished", sa.TIMESTAMP(), nullable=True),
        sa.Column("has_finished_scraping", sa.Boolean(), nullable=True),
        sa.Column("has_been_indexed", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("scrape_id"),
    )
    op.create_table(
        "tbl_subject",
        sa.Column("subject_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("subject", sa.VARCHAR(length=128), nullable=True),
        sa.Column("subject_long", sa.VARCHAR(length=128), nullable=True),
        sa.PrimaryKeyConstraint("subject_id"),
    )
    op.create_table(
        "tbl_word",
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column("word", sa.VARCHAR(length=255), nullable=True),
        sa.PrimaryKeyConstraint("word_id"),
        sa.UniqueConstraint("word"),
    )
    op.create_index("word_index", "tbl_word", ["word"], unique=False)
    op.create_table(
        "tbl_faculty",
        sa.Column("faculty_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("banner_id", sa.BINARY(length=32), nullable=False),
        sa.Column("scrape_id", sa.Integer(), nullable=True),
        sa.Column("instructor_name", sa.VARCHAR(length=128), nullable=True),
        sa.Column("instructor_email", sa.VARCHAR(length=128), nullable=True),
        sa.Column("instructor_rating", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["scrape_id"],
            ["tbl_scrape_history.scrape_id"],
        ),
        sa.PrimaryKeyConstraint("faculty_id"),
        sa.UniqueConstraint("banner_id"),
    )
    op.create_table(
        "tbl_report",
        sa.Column("report_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("report_type", sa.Integer(), nullable=True),
        sa.Column("operating_system", sa.Integer(), nullable=True),
        sa.Column("browser_description", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["browser_description"],
            ["tbl_browser.browser_id"],
        ),
        sa.ForeignKeyConstraint(
            ["operating_system"],
            ["tbl_operating_system.os_id"],
        ),
        sa.ForeignKeyConstraint(
            ["report_type"],
            ["tbl_report_type.report_type_id"],
        ),
        sa.PrimaryKeyConstraint("report_id"),
    )
    op.create_table(
        "tbl_restriction",
        sa.Column("restriction_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("restriction", sa.VARCHAR(length=128), nullable=True),
        sa.Column("must_be_in", sa.Boolean(), nullable=True),
        sa.Column("restriction_type", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["restriction_type"],
            ["tbl_restriction_type.restriction_type_id"],
        ),
        sa.PrimaryKeyConstraint("restriction_id"),
    )
    op.create_table(
        "tbl_school",
        sa.Column("school_id", sa.Integer(), nullable=False),
        sa.Column("school_unique_value", sa.VARCHAR(length=128), nullable=True),
        sa.Column("subdomain", sa.VARCHAR(length=64), nullable=True),
        sa.Column("timezone", sa.VARCHAR(length=64), nullable=True),
        sa.Column("scrape_id_last", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["scrape_id_last"],
            ["tbl_scrape_history.scrape_id"],
        ),
        sa.PrimaryKeyConstraint("school_id"),
    )
    op.create_table(
        "tbl_term",
        sa.Column("term_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("school_id", sa.Integer(), nullable=True),
        sa.Column("real_term_id", sa.Integer(), nullable=True),
        sa.Column("term_description", sa.VARCHAR(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["tbl_school.school_id"],
        ),
        sa.PrimaryKeyConstraint("term_id"),
        sa.UniqueConstraint("school_id", "real_term_id", name="_term_id_school_id_constraint"),
    )
    op.create_table(
        "tbl_course",
        sa.Column("course_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("term_id", sa.Integer(), nullable=True),
        sa.Column("course_code", sa.VARCHAR(length=32), nullable=True),
        sa.Column("course_description", sa.VARCHAR(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["tbl_term.term_id"],
        ),
        sa.PrimaryKeyConstraint("course_id"),
        sa.UniqueConstraint("term_id", "course_code", name="_term_id_course_code_constraint"),
    )
    op.create_table(
        "tbl_course_data",
        sa.Column("course_data_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=True),
        sa.Column("scrape_id", sa.Integer(), nullable=True),
        sa.Column("class_type_id", sa.Integer(), nullable=True),
        sa.Column("subject_id", sa.Integer(), nullable=True),
        sa.Column("crn", sa.VARCHAR(length=32), nullable=True),
        sa.Column("course_title", sa.VARCHAR(length=128), nullable=True),
        sa.Column("campus_description", sa.VARCHAR(length=128), nullable=True),
        sa.Column("maximum_enrollment", sa.Integer(), nullable=True),
        sa.Column("current_enrollment", sa.Integer(), nullable=True),
        sa.Column("maximum_waitlist", sa.Integer(), nullable=True),
        sa.Column("current_waitlist", sa.Integer(), nullable=True),
        sa.Column("credit_hours", sa.Integer(), nullable=True),
        sa.Column("delivery", sa.VARCHAR(length=128), nullable=True),
        sa.Column("open_section", sa.Boolean(), nullable=True),
        sa.Column("link_identifier", sa.VARCHAR(length=128), nullable=True),
        sa.Column("is_section_linked", sa.Boolean(), nullable=True),
        sa.Column("sequence_number", sa.VARCHAR(length=128), nullable=True),
        sa.Column("should_be_indexed", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["class_type_id"],
            ["tbl_classtype.class_type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["tbl_course.course_id"],
        ),
        sa.ForeignKeyConstraint(
            ["scrape_id"],
            ["tbl_scrape_history.scrape_id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["tbl_subject.subject_id"],
        ),
        sa.PrimaryKeyConstraint("course_data_id"),
        sa.UniqueConstraint("course_id", "crn", name="_course_id_crn_constraint"),
    )
    op.create_table(
        "tbl_course_faculty",
        sa.Column("course_data_id", sa.Integer(), nullable=False),
        sa.Column("faculty_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_data_id"],
            ["tbl_course_data.course_data_id"],
        ),
        sa.ForeignKeyConstraint(
            ["faculty_id"],
            ["tbl_faculty.faculty_id"],
        ),
        sa.PrimaryKeyConstraint("course_data_id", "faculty_id"),
    )
    op.create_table(
        "tbl_course_restriction",
        sa.Column("course_data_id", sa.Integer(), nullable=False),
        sa.Column("restriction_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_data_id"],
            ["tbl_course_data.course_data_id"],
        ),
        sa.ForeignKeyConstraint(
            ["restriction_id"],
            ["tbl_restriction.restriction_id"],
        ),
        sa.PrimaryKeyConstraint("course_data_id", "restriction_id"),
    )
    op.create_table(
        "tbl_meeting",
        sa.Column("meeting_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("meeting_hash", sa.BINARY(length=32), nullable=False),
        sa.Column("course_data_id", sa.Integer(), nullable=True),
        sa.Column("term_id", sa.Integer(), nullable=True),
        sa.Column("crn", sa.VARCHAR(length=32), nullable=True),
        sa.Column("building", sa.VARCHAR(length=128), nullable=True),
        sa.Column("building_description", sa.VARCHAR(length=128), nullable=True),
        sa.Column("meeting_type", sa.VARCHAR(length=128), nullable=True),
        sa.Column("meeting_type_description", sa.VARCHAR(length=128), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("begin_time", sa.VARCHAR(length=128), nullable=True),
        sa.Column("end_time", sa.VARCHAR(length=128), nullable=True),
        sa.Column("time_delta", sa.Integer(), nullable=True),
        sa.Column("days_of_week", sa.Integer(), nullable=True),
        sa.Column("room", sa.VARCHAR(length=128), nullable=True),
        sa.Column("category", sa.VARCHAR(length=128), nullable=True),
        sa.Column("credit_hour_session", sa.Float(), nullable=True),
        sa.Column("hours_week", sa.Float(), nullable=True),
        sa.Column("meeting_schedule_type", sa.VARCHAR(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_data_id"],
            ["tbl_course_data.course_data_id"],
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["tbl_term.term_id"],
        ),
        sa.PrimaryKeyConstraint("meeting_id"),
        sa.UniqueConstraint("meeting_hash"),
    )
    op.create_table(
        "tbl_word_course_data",
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column("course_data_id", sa.Integer(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_data_id"],
            ["tbl_course_data.course_data_id"],
        ),
        sa.ForeignKeyConstraint(
            ["word_id"],
            ["tbl_word.word_id"],
        ),
        sa.PrimaryKeyConstraint("word_id", "course_data_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tbl_word_course_data")
    op.drop_table("tbl_meeting")
    op.drop_table("tbl_course_restriction")
    op.drop_table("tbl_course_faculty")
    op.drop_table("tbl_course_data")
    op.drop_table("tbl_course")
    op.drop_table("tbl_term")
    op.drop_table("tbl_school")
    op.drop_table("tbl_restriction")
    op.drop_table("tbl_report")
    op.drop_table("tbl_faculty")
    op.drop_index("word_index", table_name="tbl_word")
    op.drop_table("tbl_word")
    op.drop_table("tbl_subject")
    op.drop_table("tbl_scrape_history")
    op.drop_table("tbl_restriction_type")
    op.drop_table("tbl_report_type")
    op.drop_table("tbl_operating_system")
    op.drop_table("tbl_classtype")
    op.drop_table("tbl_browser")
    # ### end Alembic commands ###
