"""modify user table

Revision ID: c5bfdc59d5d1
Revises: b0fbe2cf1cd1
Create Date: 2023-10-12 17:24:35.491757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5bfdc59d5d1'
down_revision: Union[str, None] = 'b0fbe2cf1cd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_user', sa.Column('display_name', sa.VARCHAR(length=128), nullable=True))
    op.add_column('tbl_user', sa.Column('is_private', sa.Boolean(), nullable=False))
    op.add_column('tbl_user', sa.Column('edited_at', sa.TIMESTAMP(), server_default=sa.sql.func.now(), onupdate=sa.sql.func.now(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_user', 'edited_at')
    op.drop_column('tbl_user', 'is_private')
    op.drop_column('tbl_user', 'display_name')
    # ### end Alembic commands ###
